### ISSUE TITLE
write fits cal memo

### ISSUE THREAD

**Issue by dannyjacobs** [HERA-Team/pyuvdata#106]

**Comment by bhazelton** [comment]
needs to go in docs/references

**Comment by plaplant** [comment]
I updated the `.tex` file on the `calfits_memo` branch, but didn't flag it for a full PR. If people are happy with it, we can merge it into master and maybe add the `.pdf` too.

**Comment by bhazelton** [comment]
I think it's close, but when I checked last I think there were still errors in the data array shapes described in the last section (they hadn't been updated for the work you did to keep the number of axes the same).

**Comment by plaplant** [comment]
Ah, didn't notice that, thanks. I'll give the whole memo another once over and push the changes.

**Comment by plaplant** [comment]
Alright, I pushed a version with the axes sizes more explicit, let me know what you guys think.

**Comment by bhazelton** [comment]
That looks better, but I think section 4.1 is still wrong in terms of the number of axes in the fits files. Didn't you change that?

**Comment by plaplant** [comment]
Oh you're right, I missed that part. I didn't bother actually reading the paragraphs at the end 😛

**Comment by plaplant** [comment]
Text has been updated

**Comment by bhazelton** [comment]
That looks great now, @plaplant. Thanks!

**Comment by bhazelton** [comment]
Done in latest PR.
